/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Bitmap(args); // new Bitmap().transform();
//        System.out.println(args[0]);
//        System.out.println(args[1]);
    }
}
